#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

(git diff HEAD --quiet)
diff=$?

if test $diff -eq 1
then
  echo "Stashed local changes before testing..."
  git stash > /dev/null
fi

yarn test:e2e

if test $diff -eq 1
then
  echo "Reapplied stashed changes before pushing..."
  git stash pop > /dev/null
fi

return